### ISSUE TITLE
Script fails during compilation step

### ISSUE THREAD

**Issue by marleygf** [Wade821/PiDrawpile#1]
Hi! I'm really excited to use this and the script seems to mostly work okay up until errors with the cmake/compilation. Should I post a log of the script/output here after I try nuking this pi and starting from scratch? I'm on the latest 64 bit on the pi400

**Comment by Wade821** [comment]
Would need more information, like which script you're using, the version number, and the output from the script. Or if you want, you could always join the Discord for Drawpile and talk to me there (Bluestrings) in the #help_server_owner channel, or send me a DM there. 

However, you just caught me at a bad time as right now the script is undergoing a LOT of changes, so nuking and restarting from scratch might be best to make sure you're on the latest version of Raspbian anyway. 

----------

I've been working on this for several weeks now, trying to get it feature complete (as well as working on Fedora Workstation and Raspbian for Desktop, eventually to include Fedora Server, Ubuntu Workstation/Server, Debian Workstation/Server. The newest version of the script also expands the capabilities to use Pi-Hole (for home network ad blocking) and RPi-Monitor (to monitor system values over time, like RAM usage, CPU, network, and so forth). It's not anywhere near done though is the only problem here. I haven't written server management scripts to work with it (finding/searching through DPREC recordings, deleting old files to manage server space, etc) as I've wanted to finish all the changes before focusing on that. 

You're welcome to try out the "testing" version of the script noted below, but I'm pretty sure I've changed it several times since then and need to finish more things before uploading another version of it and of course, it may be broken. As such, anything you do now may need to be redone from scratch in the hopefully near future once I am finished making changes. 

https://github.com/Wade821/PiDrawpile/blob/master/testing/drawpile-installer-official-build-from-sources-with-listserver-and-webadmin2

**Comment by Wade821** [comment]
The script is not completed yet, still some testing to be done and possibly changes... but the script has been updated quite a bit since this issue was updated. Can you try it and let me know how it works for you?

https://raw.githubusercontent.com/Wade821/PiDrawpile/master/testing/drawpile-installer-official-build-from-sources-with-listserver-and-webadmin2

**Comment by Wade821** [comment]
The script update is still a ways off to completion, but given there's no response I'm closing this out.
